#ifndef _CONFIGDEFS_
#define _CONFIGDEFS_ 1

#define DYNAMORIO_DEFINES "-DDRSTATS_DEMO -DX86 -DWINDOWS -DDR_HOST_X86 -DAPP_EXPORTS -DKSTATS -DANNOTATIONS -DASSEMBLE_WITH_MASM -DHAVE_MEMINFO -DHAVE_MEMINFO_QUERY -DWINDOWS_PC_SAMPLE -DDR_APP_EXPORTS"

#endif /* _CONFIGDEFS_ */
